# Site Settings
baseurl: ""
url : "https://ahmedelq.sa/"

# Blog Settings
theme_settings :
  title : Alq
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/dp.png
    username : Ahmed Helmi
    description : Interested in CompSci & MATH.
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: ahmedelq
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: ahmelq
    youtube:
    facebook:
    instagram: ahmelq

  # Disqus
  disqus_shortname: https-ahmedelq-sa

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
